config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'photos' => 'photos#index'
  get 'photos/engagement' => 'photos#engagement'
  get 'reception' => 'reception#index'
  get 'ceremony' => 'ceremony#index'

  resources :messages, :path => "guestbook"

  devise_for :admins
  devise_scope :admin do
    get "/admin" => "devise/sessions#new"
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates :message, :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ceremony_controller.rb
class CeremonyController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.all
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)

    if @message.save
      @users = ['fvilla18@gmail.com', 'agmartin7@yahoo.com']

      @users.each do |user|
        UserNotifier.send_notification(user).deliver_now
      end

      redirect_to messages_path
    else
      render 'new'
    end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    redirect_to messages_path    
  end

  private
    def message_params
      params.require(:message).permit(:message, :name)
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  require 'fastimage'

  def index
  end

  def engagement
    images = Dir.glob("app/assets/images/photos/engagement/*.jpg")
    @images_large = []
    @images_regular = []

    images.each do |image|
      if FastImage.size(image)[1] > 1000
        @images_large.push(image)
      else
        @images_regular.push(image)
      end
    end
  end
end

app/controllers/reception_controller.rb
class ReceptionController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Ariana and Fernando's Wedding - June 26, 2015"

    if page_title.empty?
        base_title
    else
        "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/ceremony_helper.rb
module CeremonyHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/reception_helper.rb
module ReceptionHelper
end

app/views/ceremony/index.html.erb
<% provide(:title, "Ceremony") %>

<div class="jumbotron ceremony">
  <div class="container">
    <div class="row">
      <div class="col-sm-11 col-md-9 col-lg-8 center-block ceremony-info">
        <h2 class="text-center">St. Denis Catholic Church</h2>
        <%= image_tag('ceremony/church-front.jpg', class: "img-responsive") %>

        <p>Address: 2151 S Diamond Bar Blvd, Diamond Bar, CA 91765<a href="#ceremony-map"> (View Map)</a></p>
        <p>Website: <a href="http://www.stdenis.org/" target="_blank">www.stdenis.org</a></p>
        <hr>
        <p>Friday, June 26, 2015</p>
        <p>Ceremony: 1:30pm</p>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid ceremony-map">
  <div class="jumbotron">
    <div id="ceremony-map"></div>
  </div>
</div>

app/views/home/index.html.erb
<div class="jumbotron home">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-6 collage">
        <%= link_to image_tag('home/collage.png', :class=> "animated fadeInLeft img-responsive"), photos_path %>
      </div>
      <div class="col-xs-12 col-sm-4 col-md-6 story-link text-center animated zoomInRight">
        <%= link_to "Our Story", {anchor: "our-story"}%> <br> <i class="fa fa-chevron-down"></i>
      </div>
    </div>
  </div>
</div>

<div class="jumbotron story text-center">
  <div class="container-fluid story-overlay">
    <div class="row">
      <div class="col-xs-12" id="our-story">
        <h2>Our Story</h2>
      </div>
    </div>

    <div class="row">
      <div class="col-md-5 col-md-offset-1">
        <h3>Her Version</h3>
        <p>Once upon a time there lived a very clumsy princess named Ariana. Her equilibrium and spatial awareness were slightly skewed, and because of that she opted to steer clear of bats (and all sports for that matter). Upon being invited to join a softball team, the very clumsy princess said she wanted to avoid any injuries but would love to participate in some way, shape or form. The team members brainstormed and alas the team captain said, “I think you should be the team mom!”</p>
        <p>Visions of tiny juice bottles and brown paper bags filled with treats began to fill her mind. “Yes, I accept that challenge!” she declared. Her fellow princess, the lovely Emma, suggested she attend the games to check out “Big Fern”- a fellow she thought would be a good match for the single “team mom”. The thought of a potentially hot athlete with which she could hypothetically create athletically inclined children was so enticing. I digress… It was just a good idea. </p>
        <p>The big day of the game arrived, and the princess prepared twelve brown paper bags with oranges and mini apple juices. “This guy will think I am domesticated and creative,” she thought. She arrived at the Friday night game wearing short shorts and a big sweatshirt because it was cold, of course. She caught one glimpse of the prince, and thought he was what her mom would call “a hunk”. He, of course, did not look at her until the end of the game when it was time to disperse the snacks. Emma introduced them. The princess could not look at him in the eyes because she did not want to seem too interested, so she casually looked down at the ground while being introduced. She was sure that was what got him.</p>
        <p>The team went out for pizza and alcoholic beverages after the game, and the “team mom” and “Big Fern” were strategically placed next to each other. They exchanged one word or maybe four (“Pass me the plate”). “He is not interested, ” she thought. She vowed to continue to attend games, though, and fulfill her duties as “team mom”.  A few games came and went and she stopped wearing the short shorts. It slowly turned into tight jeans and sweatshirts.
        One day as she sat in the stands with her twelve paper bags and a stack of notecards for an upcoming test, she heard a voice and looked up. It was “Big Fern”. He was running late to the game, and he asked her why she did not want to play. She said she was clumsy and laughed nervously. He giggled too and quickly walked away to join the rest of the players.</p>
        <p>That night something magical happened. During the weekly excursion to the royal bar and pizza parlor, the once reserved and quiet “Big Fern” willingly elected to sit next to the princess; they laughed and talked all night long. No phone numbers were exchanged, but he requested her on her royal Facebook- a true sign of courtship. They exchanged very long messages for two weeks before he asked for her phone number. Then they talked every day, or maybe she talked and he listened quietly.  They soon became an item.</p>
        <p>After two years of dating, he popped the question. He arrived with a Christmas present on Christmas Eve. It was very nicely wrapped in a fairly large box. It had a nice card at the top. She opened the card and it said, “To the woman I love… I’m sorry I cannot give you what you deserve, but accept this unique gift instead”. She opened the big box and there was a picture frame. He asked her to set it aside. Then there was a smaller gift box underneath that box and she opened it. It contained a set of preassembled puzzle pieces, which he asked her to put into the frame. That process continued with a few more boxes. She continued to add the puzzle pieces and they started to spell something. When she finally added the last pieces, she was able to decode the message- “Yes, that’s what she said.” </p>
        <p>He then grabbed the last tiny box, opened it and got down on one knee. He said, “Ariana Martin, will you marry me?” He used her full name, which was quite impressive.</p>
        <p>Knowing that he would have to open her gift to him, she said, “Are you sure? I only bought you a sweater.” He said yes and so did she. They shared a warm embrace, and slowly but very steadily thereafter they undertook the task of planning their nuptials.</p>
        <p>I would like to think that this is my fairytale ☺ </p>
      </div>

      <div class="col-md-5">
        <h3>His Version</h3>
        <p>I got her…the end ;)</p>
        <%= image_tag('home/yes.png', :class=> "yes-img hidden-xs hidden-sm img-responsive") %>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid registry">
  <div class="row text-center" id="registry">
    <div class="col-xs-12">
      <h1>Our Registries</h1>
    </div>

    <div class="col-xs-12 col-sm-3 col-centered">
      <%= link_to image_tag('home/honeyfund.png', class: 'img-responsive'), "http://www.honeyfund.com/wedding/ariandfern", target: "blank"  %> 
    </div>

    <div class="col-xs-12 col-sm-3 col-centered">
      <%= link_to image_tag('home/target.png', class: 'img-responsive'), "http://www.target.com/gift-registry/giftgiver?registryId=xKc0I-85eueoWl1v_8Xl4g&registryType=WEDDING", target: "blank"  %> 
    </div>

    <div class="col-xs-12 col-sm-3 col-centered">
      <%= link_to image_tag('home/bbb.png', class: 'img-responsive'), "http://www.bedbathandbeyond.com/store/giftregistry/view_registry_guest.jsp?pwsToken=&eventType=Wedding&registryId=542022858", target: "blank" %> 
    </div>
  </div>
</div>

<div class="container-fluid hotel-info">
  <div class="row" id="hotel">
    <div class="col xs-12">
      <h1 class="text-center">Hotel Information</h1>
    </div>

    <div class="info-container">
      <div class="col-sm-6 col-md-4 col-md-offset-2">
        <%= link_to image_tag('home/embassy.jpg', class: 'img-responsive'), "http://embassysuites.hilton.com/en/es/groups/personalized/L/LAXBRES-XMV-20150625/index.jhtml", target: "blank" %>
      </div>

      <div class="col-sm-6 col-md-4 text-center">
        <h3>Embassy Suites Brea</h3>
        <p>A block of rooms has been reserved for June 25, 2015 - June 27, 2015. The special room rate will be available until June 11th or until the group block is sold-out, whichever comes first.</p>
        <p>Free shuttle service to and from the Nixon Library is provided until midnight on the day of the Wedding.</p>
        <p>Address: 900 East Birch Street, Brea, California 92821 <a href="#hotel-map">(View Map)</a></p>
        <br>
        <h4><a href="http://embassysuites.hilton.com/en/es/groups/personalized/L/LAXBRES-XMV-20150625/index.jhtml" target="_blank">Book Online Now</a></h4>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid hotel-map">
  <div class="jumbotron">
    <div id="hotel-map"></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="description" content="Ariana Martin and Fernando Villasenor wedding. June 26, 2015">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><%= full_title(yield(:title)) %></title>
    
    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <link href='http://fonts.googleapis.com/css?family=Dancing+Script' rel='stylesheet' type='text/css'>

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <script src="http://maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
    <script src='http://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Ariana and Fernando Wedding", root_path, :class => "navbar-brand" %>
          <%= image_tag('doves.png', class: "hidden-xs hidden-sm doves") %>
          <%= image_tag('heart.png', class: "hidden-xs hidden-sm hidden-md heart")%>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right text-center">
            <li><%= link_to "<i class='fa fa-bell'></i> Ceremony".html_safe, ceremony_path%></li>
            <li><%= link_to "<i class='fa fa-glass'></i> Reception".html_safe, reception_path%></li>
            <li><%= link_to "<i class='fa fa-gift'></i> Registry".html_safe, root_path + '#registry'%></li>
            <li><%= link_to "<i class='fa fa-bed'></i> Hotel".html_safe, root_path + '#hotel'%></li>
            <li><%= link_to "<i class='fa fa-camera'></i> Photos".html_safe, photos_path%></li>
            <li><%= link_to "<i class='fa fa-pencil'></i> Guest Book".html_safe, messages_path%></li>
          </ul>
        </div>
      </div>
    </nav>

    <%= yield %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-49593330-4', 'auto');
      ga('send', 'pageview');
    </script>
  </body>
</html>

app/views/messages/index.html.erb
<% provide(:title, "Guest Book") %>

<div class="container-fluid guest-book text-center">
  <div class="row">
    <div class="col-sm-12">
      <h1>Guest Book</h1>
      <p>We would love it if you would take the time to jot down your thoughts and messages.</p>
      <p>-Love Ari and Fern</p>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <%= link_to "Sign Our Guest Book", new_message_path %>
    </div>
  </div>

  <div class="row" id="messages-container">
    <% @messages.each do |message| %>
      <div class="col-xs-6 col-sm-3 message-box">
        <div class="message">
          <p class="message-text">"<%= message.message %>"</p>
          <p class="message-name">-<%= message.name %> (<%= message.created_at.strftime('%b %e, %l:%M %p') %>)</p>
          <% if admin_signed_in? %>
            <p><%= link_to "Delete", message_path(message), method: :delete, data: { confirm: "Are you sure?" } %></p>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/messages/new.html.erb
<% provide(:title, "Guest Book | New Message") %>

<div class="container guest-book text-center">
  <div class="row">
    <div class="col-sm-12">
      <h1>Sign the Guest Book</h1>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <%= form_for @message, :html => {class: "form-horizontal"} do |f| %>
        <% if @message.errors.any? %>
          <div id="error_explanation">
            <h4>
              <%= pluralize(@message.errors.count, "error") %> prohibited
              this message from being saved:
            </h4>
              <% @message.errors.full_messages.each do |msg| %>
                <p><%= msg %></p>
              <% end %>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.text_area :message, class: "form-control", rows: 5, placeholder: "Enter your message..."  %>
        </div>

        <div class="form-group">
          <%= f.text_field :name, class: "form-control", placeholder: "Your name"  %>
        </div>

        <div class="form-group">
          <%= f.submit "Post Message", class: "btn btn-default"%>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    &laquo <%= link_to "Go back", messages_path %>
  </div>
</div>

app/views/photos/engagement.html.erb
<% provide(:title, "Engagement Photos") %>

<div class="container-fluid photos">
  <h1 class="text-center title">Engagement Photos</h1>

  <% @images_regular.each do |image| %>
    <div class="col-sm-3">
      <%= link_to(image_tag("photos/engagement/#{image.split('/').last}", class: "img-responsive thumbnail regular", lazy: true), image_path("photos/engagement/#{image.split('/').last}"), data: {lightbox: :engagement}) %>
    </div>
  <% end %>

  <% @images_large.each do |image| %>
    <div class="col-sm-3">
      <%= link_to(image_tag("photos/engagement/#{image.split('/').last}", class: "img-responsive thumbnail large", lazy: true), image_path("photos/engagement/#{image.split('/').last}"), data: {lightbox: :engagement}) %>
    </div>
  <% end %>
</div>

app/views/photos/index.html.erb
<% provide(:title, "Photo Galleries") %>

<div class="jumbotron galleries">
  <div class="container">
    <div class="row">
      <h1 class="text-center title">Photo Galleries</h1>

      <div class="col-sm-6 col-sm-offset-3">
        <%= link_to image_tag("photos/engagement/engagement37.jpg", class: "img-responsive thumbnail"), :action => 'engagement'%>
        <h2 class="text-center">Engagement</h2>
      </div>

      <!--
      <div class="col-sm-6">
        <%= image_tag("photos/coming-soon.png", class: "img-responsive thumbnail") %>
        <h2 class="text-center">Wedding</h2>
        -->
      </div>
    </div>
  </div>
</div>

app/views/reception/index.html.erb
<% provide(:title, "Reception") %>

<div class="jumbotron reception">
  <div class="container">
    <div class="row">
      <div class="col-sm-11 col-md-9 col-lg-8 center-block reception-info">
        <h2 class="text-center">Richard Nixon Library & Museum</h2>
        <%= image_tag('reception/library-entrance.jpg', class: "img-responsive") %>

        <p>Address:18001 Yorba Linda Blvd., Yorba Linda, CA 92886  <a href="#reception-map">(View Map)</a></p>
        <p>Website: <a href="http://www.nixonlibrary.gov/" target="_blank">www.nixonlibrary.gov</a></p>
        <hr>
        <p>Friday, June 26, 2015</p>
        <p>Cocktail Hour: 5pm - 6pm</p>
        <p>Dinner: 6pm</p>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid reception-map">
  <div class="jumbotron">
    <div id="reception-map"></div>
  </div>
</div>

app/views/user_notifier/send_notification.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <p><a href="http://www.ariandfern.com/guestbook">View the guestbook now</a></p>
  </body>
</html>